export const ROUTES = {
    DEFAULT: '/',
    404: '/404',
    WELCOME: '/welcome',
    SETTINGS: '/settings',
    SIGN_IN: '/sign-in',
    SIGN_UP: '/sign-up',
    FORGOT_PASSWORD: '/forgot-password',
    MASTER_PASSWORD: '/master-password',
    JOURNALS: '/journals',
    JOURNAL_VIEW: '/journals/view',
    JOURNAL_EDIT: '/journals/edit',
    JOURNAL_ADD: '/journals/add',
    PERSONAL: '/personal',
    PERSONAL_CREATE: '/personal/create',
    PERSONAL_PASSWORD_VIEW: '/personal/passwords',
    PERSONAL_PASSWORDS: '/personal/passwords',
    PERSONAL_WALLETS: '/personal/cryptoWallets',
    PERSONAL_CARDS: '/personal/cards',
    IDEAS: '/ideas',
    TASKS: '/tasks',
    FOCUS: '/focus/log',
};
